### ISSUE TITLE
Can StrangIOC work with Unity micro mscorlib?

### ISSUE THREAD

**Issue by tvhnet2014** [strangeioc/strangeioc#138]

**Comment by fogAndWhisky** [comment]
I'll qualify my answer slightly. I haven't been frontline developing for iOS for a while, so if anyone who does this regularly wants to comment please do so. Mscorlib is the standard reduced size library for deployment on iOS, and we know that a lot of Strange products are released for iOS. So the answer should be yes, since we haven't had any complaints suggesting otherwise.
