### ISSUE TITLE
Support for nested contexts

### ISSUE THREAD

**Issue by Lorodion** [strangeioc/strangeioc#143]
I am making a spaceship game which currently doesn't use DI, but I have read a lot about Strange and would like to use it. Some basic info about my game:
- Each player has one ship.
- Ships can be docked inside bigger ships.
- Local co-op support.

I was thinking about making each ship a context - that way I could inject ship configuration, player input etc. to the ship's submodules (which are sub transforms of the ship). The ship may be nested when docked.
This does however not seem to be entirely achievable using Strange.
How would you use Strange in this case?

**Comment by fogAndWhisky** [comment]
What you're describing does not only sound achievable with Strange, it describes a core use case. From very early on, Strange has supported the notion of multiple nested contexts. If you pull the repo and look in the examples section, you'll see a very simple version of what you describe. You can have multiple contexts per scene, or multiple scenes within a single context.

Now, how you go about structuring your contexts depends on a lot on particulars. Knowing that you have ships docked within ships doesn't necessarily make me think that each ship qualifies as its own context. To some degree, this depends on the complexity of a 'ship' and the way in which cooperative action is intended to be achieved. There are, of course, many routes to doing this.

I rather suspect my approach would be to think not in terms of ships but in terms of modules. A module would be defined as a collection of one or more modules, including itself. In this regard, a ship is nothing more than a module of modules, and a larger ship is simply a collection of even more modules (that may or may not be other ships). If each module is a context, the nesting structure becomes obvious and fairly trivial. 

The only possible complication I see is local communication within context groups, though this can be solved fairly trivially using dynamically named dispatchers. 

As a final note, because you're talking about cooperative behavior, consider that Strange is a client side framework. The app should be structured as it would matter to the player, and no larger. Assuming this is intended as some sort of massively multiplayer experience, it would be grossly inefficient to build the entire list of nested contexts based on a broader game world.

Hope that helps!

**Comment by WillzZz** [comment]
The popcap guys did a bunch of work on something like this a long time ago.  It's very doable. It's also similar to the dynamic injection discussions we've had in the past. It's one of those problems that has solutions, but I've never been quite happy with the difficulty of implementation. If you've got any ideas or code to help solve this sort of problem, by all means :)

**Comment by Lorodion** [comment]
Thanks for the help! Sounds like I could create contexts dynamically then just as I create ships. Does that mean that a context only injects in its own transform hierarchy? Or how are contexts scoped when you have several in the scene? What about injection in classes that are not tied to Unity (that are not MonoBehaviours)?

And another thing, is it possible to redo injection at a later stage (long after object creation)? Say I create a ship module at start and later on it changes owner, could I redo the injection to get for example a new player input instance?

**Comment by WillzZz** [comment]
Ok, starting from the top:

Yes, a context will only inject within its hierarchy, with one exception for our static firstContext fallback.

Contexts will inject in to anything within the commandbinder/injectionbinder/mediationbinder/etc that you have mapped. MBs are definitely not required in any way.

It is not possible to re-inject. Marc had a concept of Live Bindings he was working on last year, but I'm not sure it went anywhere. I'm sure he'd be happy to discuss what he was thinking.

**Comment by fogAndWhisky** [comment]
We didn't go very far with live bindings, mostly because it received pretty lukewarm feedback from the community. The notion was that you could declare a binding as "live"...thus when it changed, all clients would receive an updated instance. The work to achieve this was non-trivial, and, as I say, the idea was not universally loved. 

With all this said, there are plenty of ways to achieve this. Most obviously, a ChangeOfOwnerSignal/Command pair containing the old owner object, the new owner object, and the transferred object would completely solve this. Injections are, at the end of the day, nothing but public setters.

**Comment by srimarc** [comment]
Contexts are like enclosed bubbles. You can define the same binding in different Contexts just fine and they'll respect each other precisely because they know nothing about each other. So the context into which you set the binding determines the injections for instances instantiated within that Context.

(The only exception I can think of would be if you were wrapping something that a third party had previously written as a Singleton. If there's only a single static instance, then nothing Strange does can really get around that problem.)

The Unity-ness (or lack thereof) doesn't enter into it.
