### ISSUE TITLE
Routine Runner integration

### ISSUE THREAD

**Issue by optimisez** [strangeioc/strangeioc#151]
I found this at StrangeRock. Do u guys plan to integrate this with eschewing MonoBehaviours altogether? 
https://github.com/strangeioc/strangerocks/blob/master/StrangeRocks/Assets/scripts/strangerocks/common/util/RoutineRunner.cs

**Comment by fogAndWhisky** [comment]
Not quite sure what your question is. Coroutines are tied to MonoBehaviours. They shouldn't be, but they are. We don't advocate getting rid of MonoBehaviours particularly, but the plain fact is that things tied to MonoBehaviours are hard to test. Abstracting the idea of routines this way gives non-MB classess access to coroutines in a way that allows unit testing. It's a particularly useful example in the StrangeRocks sample app, because it demonstrates a pattern you can emulate when you want to leverage MB-tied services in ways that can be accessed by code that doesn't want or need to be related to the MB world.

**Comment by optimisez** [comment]
So, will Routine Runner will be integrated into StrangeIOC for new version?

**Comment by fogAndWhisky** [comment]
No. RoutineRunner is simply an example of a thing Strange lets you do. It is not itself a Strange component.
