### ISSUE TITLE
Listing of Supported Platforms & Unity Versions

### ISSUE THREAD

**Issue by senorsombrero** [strangeioc/strangeioc#154]
After browsing the documentation and searching the repo, developer blog, and google I was not able to find a list of the platforms that StrangeIoC is compatible with.  Coming from the perspective of someone considering using StrangeIoC this is definitely information that I need to know before making my choice.  My question is: Which platforms does StrangeIoC compatable with?  As well as which versions of Unity? and I woud also like to request this information is added to the top level readme of the repo to make it easier for future users to find this information.

**Comment by unitymarc** [comment]
That's a very reasonable ask. Unity versions is simple: Anything 4.0+ should work with Strange.

Platforms is a little less certain, but I'll try to put together an official list. At the present time, my understanding is that we've validated on the following:
Mac, Windows, Browser (Chrome is obviously a dicey proposition at the present time, but that's nothing to do with Strange), iOS, Android, Windows Phone 8.0 (not 8.1). I'll try to get you a definitive list, which I'll then post on our README and on the site (probably in the FAQ).

**Comment by andgeno** [comment]
Hi, could you please explain why WP8.0 is support andt WP8.1 is not. I assume that you actually meant that Unity's target platform "Windows Phone 8" is supported while "Windows Store" (which includes SDK 8.0, 8.1, Phone 8.1, Universal 8.1) is not. Is that correct?

**Comment by WillzZz** [comment]
WinRT. 

Windows Phone 8.1 removes support for Silverlight(.net as you know it), and enables only WinRT/metroblue. 8.0 has both. WinRT is something of a sandboxing of existing .net and changes most of the APIs in a breaking fashion. Most of the API remains, but under different packages. It's pretty frustrating.

Strange (and most .net code) requires a near re-write to make this work, we've opted against it. It might be doable. Truth be told I'm not sure all of the reflection APIs are available, as I haven't looked.

**Comment by andgeno** [comment]
Ok, thank you for the clarification. :)

**Comment by unitymarc** [comment]
Based on a conversation with @WillzZz here's a provisional list. We're working to make this solid to the best of our knowledge. Understand that this is a shifting target, and there may be details we've overlooked.

**Strange Works On**
Android
Gear VR :exclamation:
iOS
Linux Standalone
Mac Standalone
Oculus Rift :exclamation:
Steam :exclamation:
Unity Editor :bangbang:
WebGL
WebPlayer
Windows Phone 8.0
Windows Standalone

**Strange Does not Work**
Playstation 4 :zap:
Wii U :zap:
Windows Phone 8.1 (this is probably never going to work)
Windows Store Apps
XBox One :zap:

**Unsure at Present**
*A lot of these are unsure because we've not looked into it, and (to the best of our knowledge) no one else has done so. If you have certain knowledge on any of these, we'd love to hear about it.*
Android TV
Blackberry
Playstation 3
Playstation Vita
Samsung Smart TV
Tizen
XBox 360

:exclamation: Presuming the driving platform is supported.
:bangbang: Strange 1.0 will support Unity Editor extensions built on top of StrangeIoC
:zap: @WillzZz is looking into this one to see if he can solve it. He considers it one of his highest priorities.

**Comment by senorsombrero** [comment]
Thanks Marc and good luck @WillzZz.  I'm interested in learning more about why these platforms are not supported.

**Comment by fogAndWhisky** [comment]
@WillzZz explains the problem with Win 8.1 above. Windows Store problem is the same. There's a thread on our Google Group that goes into some detail on  the console problem.

**Comment by unitymarc** [comment]
Supported versions are now listed on the ReadMe (a link to the FAQ). With that, closing this ticket. Huzzah!
