### ISSUE TITLE
StangeIoC with new UI Event System

### ISSUE THREAD

**Issue by rmtuckerphx** [strangeioc/strangeioc#157]
I am looking for ideas on how to make the new EventSystem work with StrangeIoC. Let's say that I have multiple ContextViews similar to the multiplecontexts example. The difference being that 2 of my contexts (scene with root object as ContectView) have their own Canvas (with Panels, Buttons, etc.) and EventSystem objects. This works well when working with an individual scene to test but then when I kick off the MainContext which does an Application.LoadLevelAdditive() on the 2 scenes with the EventSystems, I get a warning in the Console:

Multiple EventSystems in scene... this is not supported
UnityEngine.EventSystems.EventSystem:OnEnable()

And the Button that I have on one of my Canvas instances no longer responds to highlight or click.

Next I tried disabling the EventSystem objects in all my scenes and then I added an EventSystem object to Main scene (sibling of MainContextView). When I run the Main scene and it gets to the scene that has the button, there are no longer any warnings in the Console but the button doesn't respond to highlight or click.

Any ideas on how to proceed? Would I need to have an EventSystem under MainContextView and then have the other scenes load and re-parent so that those ConextView instances are under MainContext then disable all EventSystems in the child scenes and possibly re-parent the use of the child EventSystems to the main EventSystem? I am not even sure how to go about this or if it will  work.

So I have two questions:
1. How do I get multiple ContextViews to work when working with each Scene separately and also when loaded by MainContextView as it pertains to the new UI: Canvas, Panel, Button, EventSystem?
2. What ways will StrangeIoC work now (and in the future) with the new UI and EventSystem so that I can take advantage of the new features and still get added benefit from StrangeIoC?

Thank you,

Mark

**Comment by fogAndWhisky** [comment]
Hi Mark, 

This is, of course, not an issue with Strange so much as the way the EventSystem was implemented by Unity. For some reason (probably motivated by a desire for "simplicity"), the EventSystem only supports a single instance...but rather than enforcing that notion with a Singleton (which in this case would actually be preferable...we could probably fix that by wrapping it inside a service class), the programmer simply warns you that what you're doing is not supported. Gee, thanks.

As with any other plugin, we can't fix the implementer's choices, but we can work with them. The most obvious way to do this (and honestly the one I do and recommend) is to not do what you're doing. Instead of trying to create multiple Canvases, I just put all my UI into a single scene. The reason I suggest this is that it's usually hard to use a system and at the same time fight against its innate structure. uGui seems designed to thwart what you're attempting.

That said, Strange exists to help you break down monolithic structures and I think we can do that here. Since only a single instance of EventSystem is allowed, simply turn the others off. When you issue your Command to load a scene, ask "Do already I have active an EventSystem?" If the answer is yes, look for any newly loaded EventSystems and set them to inactive. It's the same technique we apply with AudioListener (you're only allowed one of those too). I did a quick-and-dirty test of this, and it seems to work just fine.

Give this a whirl, see if it gets you where you need to be, and let me know the result.

**Comment by optimisez** [comment]
Can you provide a sample project for this scenario after StrangeIoC 1.0 released? Thanks.

**Comment by srimarc** [comment]
There's nothing in this scenario that relates to 1.0, particularly. And to maintain backward compatibility I don't want to use features that would cause errors for users of older versions of Unity.




But since uGui is an important feature I'll try to put together an example showing how we use it in Strange in a separate repo when I have some free time. This might not be for some while...I'm ferociously busy. If someone else were interested in throwing together a demo, we'd appreciate it.

**Comment by WillzZz** [comment]
So I have a fairly different response. I add my EventSystem at runtime as need be. Multiple canvas are definitely super important in ugui. I haven't had any serious problems with this method, as of yet (It's been roughly a year since event system was added, maybe more). I load all of my scenes dynamically and they all have canvas as well as my root context having universal canvas items (popups/tooltips/etc).

**Comment by WillzZz** [comment]
Not an issue with strange. (But happy to help, ping me on forums or direct through email)

**Comment by unitymarc** [comment]
That's a great answer @WillzZz (much better than mine)! To clarify, you strip out the EventSystem that Unity adds automatically when you select Add > UI > Button (or whatever)? Then add it programmatically with something like:

    contextView.AddComponent<EventSystem>();

Is that right?

**Comment by WillzZz** [comment]
Yup, in my shared context file I'll look for it and add if necessary. All contextViews are also canvas.
