### ISSUE TITLE
Is Lua able to call Strange library?

### ISSUE THREAD

**Issue by ZhongMin044** [strangeioc/strangeioc#172]
Hi,

StrangeIoC sounds great for game project, and we are considering it as low level framework of game system and game logic.

Meanwhile, we are considering another big strategy, that is to write game logic with script Lua.

Is it possible to call StrangeIoC API from Lua, or not?

Thanks a lot.

Zhong Min

**Comment by fogAndWhisky** [comment]
I've certainly never done this...nor to the best of my knowledge has anyone else. If you attempt it I think we'd all love to hear about the outcome, but I can't make any promises. I don't see any inherent reason it wouldn't work based on this Lua implementation as an idea of something you might be considering: http://www.dannygoodayle.com/2013/05/31/integrating-unity-with-lua-in-two-minutes/

Can you explain though _why_ you'd want to do it this way? The author above notes a possible impracticality due to Lua using reflection. Strange is very careful to manage reflection so you don't suffer performance hits from it. I don't know a lot about Lua, nor why it might be a practical choice for you. What advantages would this setup offer you?

**Comment by ZhongMin044** [comment]
Hello fogAndWhisky,

Thank you for your reply.

We are considering a low level framework for Unity3D project, and to use Lua for game logic part.
Why use Lua for game logic?
1) Then we can update game logic part after releasing game without updating the whole package; 
2) Another reason is that it's possible to reuse some code on the both frontend and backend sides with Lua.

We are new to StrangeIoC. After recent research, we think StrangeIoC is a good choice for game logic as well, do you think so?

We are a little hesitating to use StrangeIoC now. There are many technical concepts in the StrangeIoC, which requires gamers have basic knowledge of design pattern. Also, gamers need to design Model, View, Command, Mediator and so on clearly before implementing. Do you agree?

**Comment by DarkChowder** [comment]
Lua can use Strange if you make a wrapper, but IOC does not make sense for Lua, because even though you can fake objects in Lua, it's not really an object orientated language. To make a wrapper though you could create a wrapper class that called the injector, probably with some caching from properties. After that either assign the whole wrapper class, or individual properties onto the Lua interface. This would give Lua access to whatever it wanted on the class.

So the answer to your question is yes you can use strange, but not directly.

**Comment by fogAndWhisky** [comment]
Sorry, this got very stale. I'm going to close it, since the conversation was some months ago. Feel free to re-open if still relevant.

And yes, Strange does require the developer to understand MVC as well as DI and some other non-trivial programming concepts.
