### ISSUE TITLE
Delegate dissapears from invokation list of a signal.

### ISSUE THREAD

**Issue by Kreol-Dev** [strangeioc/strangeioc#174]
So, basically, what I've got is a shared between scenes context, which is first context, by the way. So, it has a crosscontext service, which provides list of savegames via a signal SignalResList  : Signal < List < string > >. I've got a main menu scene, and a play button, which loads additive Saves Scene, which has a mediator SavePanelMediator. In it - I inject two signals - SignalReqList and SignalResList - first stands for request and second for response.  Mediator OnRegister subscribes to SignalResList - OnList(List<string> saves). OnRemove - unsubscribes. 

So, the sequence works like so - provide crosscontext savegame service, then create a menu context, then on button click - create SavesScene context - subscribe to savegame service response - dispatch request - receive respone. It works until I click backbutton, wich destroyes savescontext effectively switching me back to main menu. After I click play again and savecSontextScene loads again - everything works *except* response - my OnList function doesn't get called. 

I checked via debug messages - it actually being added to invokation list of a signal, but then, as by magick dissapears from it without "removeListener" call.

**Comment by fogAndWhisky** [comment]
Let me re-phrase the problem, to make sure I understand it.

You have a Main scene with a MainContext. There's a service mapped cross-context, which I'll call the SavedGameService. You then have MenuContext and SaveSceneContext, which drives a Menu UI and a Save UI respectively. Clicking a button in MainMenu (MenuContext) takes you to the SavePanel (SaveContext). Clicking the back button destroys SaveScene/SaveContext, dropping you back in the MainMenu.

If you go from Menu to Save, everything works. The SavedGameService returns a list of saved games via the SignalResList. But if you go back to Menu and then back to Save again, the Signal fails. Is that right?

Based on this description, my hunch is that you have a dangling pointer somewhere. When a Scene is destroyed (and this has nothing to do with Strange...it's just plain ol' C#/Unity), all the objects in that scene are marked for deletion and GC. But they can't be deleted if there are still references to them. So, for example, if your SavedGameService or one of the Signals is marked cross-context from within the destroyed SaveContext (instead of MainContext), that Service/Signal will not be destroyed, and possibly won't re-instantiate cleanly when you return. In essence, you might have two of the same Signal, or just one that's lost the reference to the other objects it's supposed to communicate with.

Some things to try...

First, do not mark anything cross-context from a scene that you are repeatedly creating/destroying. CC marking should only be done in a Context that persists throughout the lifetime of the game (this is almost always the first Context).

Second, check all your object references to ensure that there's nothing left that refers to the destroyed scene/components after it's destroyed.

Use the memory profiler to confirm (or refute) my hunch that there are objects that are still in memory when they shouldn't be.

Finally, if all else fails, copy your project and then start deleting things that you're sure aren't the problem. Keep deleting until you isolate down to the particulars. Somewhere in your code, I think you'll find a reference that keeps some or all of the SceneContext from being properly deleted.

Good luck!
