### ISSUE TITLE
What is the correct overloading use for mapBindings, postBindings, addCoreComponents and instantiateCoreComponents

### ISSUE THREAD

**Issue by childnode** [strangeioc/strangeioc#179]
There are several methods in Start() fired in a sequence
* mapBindings()
* postBindings()
* addCoreComponents ()
* instantiateCoreComponents()

What is the correct overloading use for each?

I can't find a valid documentation on it.

Perhaps someone might write a "best practice" which binding / mappings should be done in which method / startup step to prevent problems.

**Comment by fogAndWhisky** [comment]
Hi @childnode,
This is mostly documented in the code and consequently in the Doxygen docs here:
http://strangeioc.github.io/strangeioc/docs/html/classstrange_1_1extensions_1_1context_1_1impl_1_1_context.html

The correct sequence is:

    addCoreComponents();
    instantiateCoreComponents();
    mapBindings();
    postBindings();

To elaborate on the code comments...

*addCoreComponents()* creates the mappings for the main components in a Context. Generally, developers never need to touch this, since MVCSContext does it for you.

*instantiateCoreComponents()* does actual instantiation of all the bindings in addCoreComponents. Again, this is usually of no concern to the developer, since MVCSContext also does this. The only time these two methods come into play is if you decide to write a custom context that descends directly from Context or CrossContext.

*mapBindings()* is the method of most interest to most developers. It's where all your bindings go.

*postBindings()* is a nicety. It's there so you can logically trigger something, safe in the knowledge that all the mappings in mapBindings are complete, but before the first Command has been triggered. So, for example, if you needed to immediately instantiate something you had just mapped, postBindings would be the place to do it.

**Comment by childnode** [comment]
1. thank you for that clarification

2. if it would be that easy to read the comments, I wouldn't ask you to improve the documentation

3. doc blocks like "Override to add componentry. Or just extend MVCSContext. " and "Override to map project-specific bindings." is as helpful as "write some code, cross your fingers and put s.th. in and s.th. will come out"

4. it's not recommended to override base documentation with these stubs, or as it seems to be: the more concrete Implementation has more documentation than it's base class ... really?
http://strangeioc.github.io/strangeioc/docs/html/classstrange_1_1extensions_1_1context_1_1impl_1_1_m_v_c_s_context.html#aad55996545681bce820c04f1b8ba7b04 => https://github.com/strangeioc/strangeioc/blob/master/StrangeIoC/scripts/strange/extensions/context/impl/MVCSContext.cs#L229

5. aside this one litte perhaps helpful line of docblock on `MVCSContext.addCoreComponents`

> Although you can override this method, it is recommended that you provide all your application bindings in mapBindings(). 

I really don't get what "This is mostly documented" means? Or do I read other code than you? Please let me know. But I'm happy that is is "done" and "answered" to you, albeit the documentation should be done not in an ticket but in code documentation website?! Sorry, yes that's sarcasm...

6. if `addCoreComponents` is only for Framework initialization, why is it then not implemented / made final/sealed? (yes, valid point would be: this might be done for MVCSContext but not for CrossContext nor for Context itself

7. if `mapBindings` reflects what `addCoreComponts` does for the backend, why this splitting? 
and `postBindings` sounds like the equivalent to `instantiateCoreComponents`

With kind regards,
~Marcel

P.S: The question is not that irrelevant, because of several issues that might come up during "bootstrap" when "binder is in wrong state" or so, there are some not so helpful exceptions for new developers and they really don't get it what they have done wrong.

**Comment by fogAndWhisky** [comment]
@childnode I'm not sure you appreciate how rude your reply sounds. I'm not often given to helping people who are sarcastic or self-entitled...my time is too valuable for that. That said, I'm giving you the benefit of the doubt, since my main motivation for being here is that I like to help people.

Answers:
2. You asked for clarification, which I gave you. If you feel the documentation needs improvement, you can issue a PR, or have conversations like this one where I or another member of the community can help you understand better. We also have a website, a forum, a blog, FB and Tw streams, all of which are good places to learn things you're having difficulty with.

3. Those are not blocks. They mean what they say. We try to comment thoroughly, but not too much, then add additional notes via documentation, such as the blog or the BSHT. If they're insufficient, I refer you to answer 2.

4. I'm not sure I understand this question. MVCSContext has a little more documentation because it's the main use case. I.e., we expect most people to start by using MVCSContext, since that's the simplest path.

5. Again, not sure I understand you. addCoreComponents does exactly what it says on the tin: it adds the core components. How much clearer could it be?

6. addCoreComponents isn't final/sealed because this is a flexible framework and we allow you to rewrite and override a ton of things. There are good use cases for doing so (if, for example, you wanted to re-write the Injector and use your own), but they tend to be advanced cases, so we don't document them in-line.

7. Yes, mapBindings/postBindings are basically the same relationship as addCoreComponents/instantiateCoreComponents. Why split? Single responsibility, for one thing. Each method has a job to do, and the code is more self-documenting when you see by name what each step does, and the developer has options about what specifically to override. There's an order to the methods, too, such that the core components are ready to use before mapBindings is called. By breaking it down in this way, for the vast majority of use cases, the only methods that have to be overridden are mapBindings and Launch. They're very clean (there's nothing in either) so it doesn't mess up if you forget to call the base method.

8. As I said, postBindings is there to allow you to handle things that happen after mapping is complete. That doesn't mean MVCSContext doesn't need to do things after mapping is complete. Maybe I've thrown you with the term 'nicety'...we could have put those lines of code in a separate method to which you had no access, I guess. But we put them where we think they belong.

Since you're looking for more insight, you should probably check out our blog...particularly all the links to the new documentation that's in the works for v1. This might be a good place to start: https://strangeioc.wordpress.com/2015/05/01/its-big-its-strange-and-im-rewriting-it/

I hear frustration behind your response, and I'm not deaf to it. Many devs experience a lot of frustration when learning Strange. I wish we had an easier way to get people up and running with less of that. But most devs -- at least the ones we hear from -- seem to get through it, have an "a ha!" moment, and then proceed to be massively productive with the framework. I hope that describes your journey.
