### ISSUE TITLE
AddListener after Dispatch

### ISSUE THREAD

**Issue by wangshunping** [strangeioc/strangeioc#225]
Hello.

I am a newbiw in strangeIOC. It is amazing project But i have a question now.

i have Instantiate an popup View (of course it attached a "View" script file)

```
	public void buttonClick() {
			Instantiate(popupHireInfoGameObject);
			// popupHireInfoGameObject.SetActive(true);
			hireButtonClicked.Dispatch();
		} 
```

and dispatch signal from command file to update view content.
but the mediate is AddListen after i have dispatch back. thus I can not update my view content

```
	public override void OnRegister() {
			// view.hireButtonClick.AddListener(hireFunc);

			// update signal
			updateHireInfoSignal.AddListener(onHireInfoUpdate);
			print ("after add lister");
		}
```

what i can do for that?

i try to WaitForSecond , but it is not a good idea.

would you mind give me some help?

**Comment by WillzZz** [comment]
The issue is you're instantiating your object, which isn't going to happen immediately. Think of Instantiate meaning "Please queue this for creation". Hence, you're firing a signal which isn't being listened to yet.

My recommendation for this particular case is to utilize a [Promise](https://github.com/strangeioc/strangeioc/blob/release/1.0f4/StrangeIoC/scripts/strange/extensions/promise/impl/Promise.cs) instead of a Signal.

 When you fire off a promise, it will hold it's payload indefinitely, so whenever the Mediator comes around to registering, you check the promise and either listen or immediately execute the callback. Hope that helps!

**Comment by WillzZz** [comment]
Oops, wrong button :)

**Comment by wangshunping** [comment]
i have Instantiated the popup view in Command to solve this problem , by the way, i will try Promise to get a better solve. I will let you know if i get any progress， thanks for you help.

**Comment by wangshunping** [comment]
is there a doc or demo to show how to use promise ?

**Comment by wangshunping** [comment]
by the way, i have solve my problem, so i close it.
