### ISSUE TITLE
Multiple context bindings are Failed

### ISSUE THREAD

**Issue by krishnarjun009** [strangeioc/strangeioc#242]
I had a problem with multiple context bindings. I have two context bindings, and i attached to the gameobjects. But when i run the game only one context bindings are bind, I have logincontext which binds loginview and mediator and another one is mapcontext which binds mapview and mediator, but only login view and mediator are binds. even though i checks in debug mode. code is point to mapcontext, but still not binding.? Any help for this.......... Thank you..

**Comment by WillzZz** [comment]
Could you post some of your code? Need some more info. Thanks!

**Comment by krishnarjun009** [comment]
finally got it.. But, only when all the views are the childern of its context root, then only mediators are attached... context should be in root game object and views are it's child.. now works... but i don't know is this framework behaviour or any bug?

**Comment by krishnarjun009** [comment]
and we are using Strange for midcore games in mobile.. it's nice... can you make [Inject] public someclass somename {get;set;} as private? post construct constructors are now private with the latest update... i dont know is this possible or not?? @WillzZz ... Thanks... We want more updates from Strange

**Comment by krishnarjun009** [comment]
Just know I observed, If mainroot context is binds all the view mediators, if any one of the panel is initially SetActive false, then mediators are not attaching to that view... they are attaching when SetActive true at runtime...

**Comment by WillzZz** [comment]
Let me do my best to address everything. Let me know if you need some additional clarity. Yes, it is by design that views must be children of contexts. I have a branch with private Injection. It's a fairly trivial change, and was a design decision that has been argued before. I don't really intend to merge it in, as the vast majority of users don't request it. As for views not being mediated until they're active, I'm not sure how you intend that to work? It would be a small processing burden to constantly poll views. The view code simply can't be run until it's active, that's the nature of a MonoBehaviour. Views do the initial step of registration in Awake, and attempt it again in Start. If they're inactive, they can't run their Awake or Start methods :) Thanks for the questions, I'm closing this as resolved.

**Comment by krishnarjun009** [comment]
thanks @WillzZz ... Now i am clear how to use Strange. Looking for new updates . Thanks.

**Comment by WillzZz** [comment]
Updates on what exactly?

**Comment by buihuuloc** [comment]
@WillzZz  Could you give me the branch with private Injection?

**Comment by WillzZz** [comment]
Sorry I mispoke. Guess I did private listensto tags. Private Inject tags shouldn't be too hard. Let me take a quick crack at it and get back to you.

**Comment by WillzZz** [comment]
move discussion to #244

**Comment by krishnarjun009** [comment]
thanks @WillzZz  .. now private injectiions are working ................. :100:
