### ISSUE TITLE
Static viewCache in MVCSContext?

### ISSUE THREAD

**Issue by yuhe00** [strangeioc/strangeioc#99]
I just spent a few hours trying to figure out why some of my views were not being mediated. Turns out they were being bound to the wrong context, because viewCache in MVCSContext is static (and yes, I'm doing some crazy stuff with multiple scenes and contexts...). I removed the static modifier, and everything seems to work as expected. Is there a particular reason for this being static? I just hope I didn't break anything.

**Comment by fogAndWhisky** [comment]
Obviously we're waaaaay late on responding to this. If memory serves, making the viewCache static allows us to catch "early risers', i.e., Views that instantiate before the ContextView. You can change that, but it means such early risers aren't guaranteed to be caught. This can be fixed in Unity with script ordering.

As this issue is so old, I'm closing with this comment. Feel free to re-open if you need to discuss further.
